### ISSUE TITLE
Sort pick list by bin

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#110]
## What is the motivation for adding/enhancing this feature?

Right now pick lists are sorted by alphabetically, there should be on option to group the items by bin also.

**Comment by Dhiraj1405** [comment]
Here's the UI: <img width="349" alt="Sort Picklist Items Settings Card (BIN ID)" src="https://user-images.githubusercontent.com/119936391/225268201-e926d953-4c18-498c-9cbd-da0fd0e60b1e.png">

This configuration can be added to the settings page (new UI) as the sorting is not changed regularly for picklist items. 

This entity [picklistandbinanditem](https://demo-oms.hotwax.io/webtools/control/FindGeneric?entityName=PicklistAndBinAndItem) contains the data which can be used to sort picklist by bin.

**Comment by dt2patel** [comment]
What are the available options in the dropdown?

**Comment by Dhiraj1405** [comment]
We currently use `picklist` API that returns the following parameters: 

`
           "locationSeqId": ",
            "productId": ,
            "productName": ,
            "quantity":,
            "picked": ,
            "binLocationNumber": ,
            "orderId": ,
            "orderItemSeqId": ,
            "shipGroupSeqId": ,
            "inventoryItemId": ,
            "picklistBinId":
  `

Out of these parameters, we already sort items by their product name, we can now include sorting items by: 
1. Order ID
2. Product ID
3. Location ID
4. Bin ID

<img width="282" alt="Sorting popover 2" src="https://user-images.githubusercontent.com/119936391/225297195-13a70a84-22d1-4901-b401-54621b02bb4c.png">

Note: Bin ID is already shared in the above image, this image only contains the rest of the sort types.

There's a code at app level which is used for sorting items by product name, this code can be referred to write a code to sort the items by other parameters.

**Comment by dt2patel** [comment]
I don't see a reason to sort by HotWax product id, additionally Bin ID already represents a logical grouping by how an order needs to be fulfilled, Order ID would be redundant since its one of the grouping logics already covered by Bins.

We can finalize:
Product name
Location ID
Bin ID

**Comment by Dhiraj1405** [comment]
Thank you for the feedback. 

UI for the available options in dropdown: 
<img width="282" alt="Sorting popover 3" src="https://user-images.githubusercontent.com/119936391/225310953-796b0868-3f58-47d8-8e18-fbd8da41f0b8.png">
