### ISSUE TITLE
Completed picklist showing option to select

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#122]
## Current behavior

If a picklist is completed then it shouldn't show options to check items on the picklist as if it is still active.

## Expected behavior

The UI should show exactly which items are picked and a disabled checkbox for items that are not picked.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by k2maan** [comment]
DIscussed, we will not show the checkbox on completed picklists.
