### ISSUE TITLE
Logged in user's picklist not showing in "me" view

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#125]
## Current behavior

Filtering the find view by "only show my picklists" is showing no results, even the ones assigned to the logged in user.

**Comment by adityasharma7** [comment]
Not able to regenerate. 

Tried with OMS: dev-oms user: aaron.wagner (default password)

Some observations:
- In progress picklist fetched for "PICKLIST_PRINTED" status only.
- Maybe facility was not fetched causing the issue, following fixes it:
https://github.com/hotwax/picking/pull/129/files#diff-d3c10a6ece79180d52468851ebe745d66365adafc59ee774a50b5687b3d42ff6R36

Let me know if the issue still persists.
