### ISSUE TITLE
Browser back button from scanner

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#128]
## Current behavior

If the camera scanner is open, the browser back button doesn't work and instead pushed the route back to the find page without closing the modal.

## Expected behavior

The scanner opens in a modal which is not technically a page so the Vue router doesn't push it onto the stack so that's why it doesn't pop when the user clicks the back button. But the expected behavior would be that if the browser navigates away from he picklist detail page, then the scanner should close automatically since its linked to that page. Any proposed solutions?

**Comment by sanskar345** [comment]
Solution - we can use an in-component navigation guard with a setup function in the picklist detail page and when the user moves away from the current route we can close the modal using the guard.

Changed Behaviour will be - If the user opens the scanner modal and clicks on the browser back button in the picklist detail page then the user moves to the previous page and modal closes.
