### ISSUE TITLE
Picklist Detail Page Not Showing All Items

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/picking#168]
## Current behavior
The picklist detail page is not displaying all the items that are supposed to be in the picklist. Currently, only a subset of items is visible, and several items are missing from the list. This issue is impacting the functionality of the application and hindering the user's ability to select the items from the picklist.

## Expected behavior
The picklist detail page should show all the items that are in the picklist. Users should be able to see and select any item from the picklist.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Roopesh127** [comment]
I want to conribute

**Comment by ymaheshwari1** [comment]
> I want to conribute

Assigned go ahead

**Comment by amansinghbais** [comment]
Closing this issue since not able to regenerate. Will reopen the issue if reoccur.
