### ISSUE TITLE
Allow picklist sorting on the Picklist detail page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/picking#171]
## What is the motivation for adding/enhancing this feature?
Currently, users lack the ability to customize the sorting order of pick list items according to their specific preferences on the Picklisr detail page. Introducing a `Sort Pick List` option directly within the Picklist detail page interface would provide users with the flexibility to override the default sorting and arrange items based on their unique requirements.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Nidbhagwat** [comment]
@Dhiraj1405 
Here is the UI Figma link:

https://www.figma.com/file/j3l0F2DioUHEuQT53NOQJY/Ionic-6-Material-UI-Kit-(Community)-(Nidhi--2023)?type=design&node-id=26093%3A69110&mode=design&t=PGaW3J9rYhBMpsVw-1
