### ISSUE TITLE
Integrate DXP Component: App Version Info on the Settings Page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/picking#176]
## What is the motivation for adding/enhancing this feature?
IntegratE of the DXP component "App Version Info" into the Settings page of the application. This addition will provide users with essential information about the version of the application they are currently using. 

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by shraddha761** [comment]
Assign this issue to me?

**Comment by k2maan** [comment]
Sure @shraddha761 go ahead

**Comment by Adameddy26** [comment]
Verified and working fine in v1.18.0.
https://jam.dev/c/4c7165a7-346e-4e5e-b14d-b321c69220c2
