### ISSUE TITLE
Custom theme file

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#2]
Add a custom theme file like in [Clienteling app](https://github.com/hotwax/clienteling/tree/main/src/theme).

This will allow any brand to customize the look and feel of any app.

**Comment by nikhilsinghhub** [comment]
I want to contribute into please assign me

**Comment by ymaheshwari1** [comment]
Sure @nikhilsinghhub

**Comment by dt2patel** [comment]
closing, already implemented
