### ISSUE TITLE
Display groupName for the pickerName

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/picking#201]
## Current behavior

Picker name is not displayed when the we open a picklist assigned to facility user login

## Expected behavior

The name should always be displayed correctly.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
https://jam.dev/c/a7e93e04-9e55-484d-acf5-40e473a6e0fa

Issue verified and working fine in 1.18.0.
