### ISSUE TITLE
While hovering on picklists, cursor property can be pointer

### ISSUE THREAD

**Issue by bashu22tiwari** [hotwax/picking#32]
## What is the motivation for adding/enhancing this feature?
While on the picklists tab, when we hover on different picklist to select then, cursor can change its property to pointer for better UI experience.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information

![Screenshot from 2021-12-16 16-28-39](https://user-images.githubusercontent.com/55925918/146364771-89d9c28f-dff5-43a1-b9f1-22e5b892962b.png)

**Comment by y0gesh02** [comment]
Ready To Contribute.

**Comment by MohitNamdev22** [comment]
@ymaheshwari1 Can I work on this issue?

**Comment by ymaheshwari1** [comment]
Sure @MohitNamdev22

**Comment by y0gesh02** [comment]
please assign me this issue

**Comment by ymaheshwari1** [comment]
> please assign me this issue

Assigned to Mohit, you can check for any other issue/
