### ISSUE TITLE
Add barcode scanner

### ISSUE THREAD

**Issue by dt2patel** [hotwax/picking#4]
## What is the motivation for adding/enhancing this feature?

Users should be able to scan products on shelves using their phone camera to make sure they are picking the right product.

## What are the acceptance criteria?

The UI should match the included mockups and select the correct item when scanned.
- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [x ] NO

## Additional information

![Picklist detail](https://user-images.githubusercontent.com/60128132/138395619-cd03961c-b44a-4ba8-9992-4859a2fc3750.png)

**Comment by nikhilsinghhub** [comment]
I want to contribute please assign me

**Comment by dt2patel** [comment]
already implemented, closing
