### ISSUE TITLE
Display a message when no picklist found

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/picking#71]
## Current behavior

If there are on picklist found then a toast is displayed and screen is empty

## Expected behavior

There should be a permanent message `There are no picklists available`

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by y0gesh02** [comment]
can I work on this

**Comment by ymaheshwari1** [comment]
Sure @y0gesh02
